src/components/ClassicButton copy/index.jsx
src/components/ClassicButton copy/style.module.css
src/components/EventCard/index.jsx
src/components/EventCard/style.module.css
src/components/RoundButton/index.jsx
src/components/RoundButton/style.module.css
src/pages/Home/index.jsx
src/pages/Home/style.module.css
src/test/Yisrael.jsx

1. כפתור קלאסי עם טקסט פנימי גנרי
2. כפתור עגול עם אייקון וטקסט מתחת גנרי
3. כרטיס אירועים המכיל מידע ספציפי ומציג אותו מסודר, כרטיס לכל אירוע
4.  דף הבית הכולל בתוכו כותרת, הצגה של כרטיסי אירועים וכפתור לפרסום אירוע

Home page and components

---

src/components/HeaderHome/index.jsx
src/components/HeaderHome/style.module.css
src/components/SecondHeader/index.jsx
src/components/SecondHeader/style.module.css
src/index.css
src/test/Sapir.jsx

1. global css.
2. שתי קומפוננטות header.

Layout client

---

src/components/EventCard/index.jsx
src/components/EventCard/style.module.css
src/pages/Home/index.jsx

שיניתי את הדמו דאטה לעברית יחד עם שינוי בסטייל במקום משמאל לימין ל ימין לשמאל

small Changes and Fixes

---

src/components/SettingsNavBar/style.module.css

changed the font size to be larger in the settings navBar

changed the font size to be larger in the settings navBar

---

src/components/BackArrow/index.jsx
src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

I finished the basic styling of the viewEvent page.

finish the style of the viewEvent page

---

src/components/EventCard/index.jsx
src/pages/Login/index.jsx

fixed apiCalles in login page  and in EventCard component

fixed apiCalles in login page  and in EventCard component.

---

src/layout/Main/index.jsx
src/pages/Login/index.jsx

changed apiCalles to axios in login.

changed apiCalles to axios in login.

---

src/components/SelectIcon/index.jsx
src/function/apiCalls.js
src/pages/NewEvent/index.jsx

upload files and navigate to the new event

New event page

---

src/components/EventCard/index.jsx
src/components/EventCard/style.module.css
src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

orgenized the eventCard and the viewEvent page.

Yisrael, orgenized the eventCard and the viewEvent page.

---

src/pages/Home/style.module.css

fixed styling on home page

---

src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

fixed styling on viewEvent

---

src/components/EventCard/index.jsx
src/components/EventCard/style.module.css
src/index.css
src/pages/Home/style.module.css
src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

'fixed my styling on viewEvent, home, eventCard'

Yisrael 'fixed my styling on viewEvent, home, eventCard'

---

src/pages/ViewEvent/style.module.css

added margin to content in viewEvent

added margin to content in viewEvent

---

src/components/EventCard/index.jsx
src/layout/Layout/index.jsx
src/layout/Main/index.jsx
src/pages/Home/index.jsx
src/pages/Login/index.jsx

fixed user verify in the app

---

src/pages/Registeretion/index.jsx
src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

'fixed registretion, changed to apiCalles and added promise handle

fixed registretion, changed to apiCalles and added promise handle

---

src/layout/Main/index.jsx
src/pages/ViewEvent/index.jsx

'fixed payment status and deleted logs'

fixed payment status and deleted logs

---

src/function/apiCalls.js
src/layout/Main/index.jsx
src/pages/ViewEvent/index.jsx

'finished publish button and fixed aouthentication bug in verifyToken function

Yisrael 'finished publish button and fixed aouthentication bug in verifyToken function

---

src/components/EventCard/index.jsx
src/components/EventCard/style.module.css
src/pages/ViewEvent/style.module.css

'edit the load button and the color of date in view event

edit the load button and the color of date in view event

---

src/components/ClassicButton copy/index.jsx
src/components/ClassicButton copy/style.module.css
src/components/SelectIcon/index.jsx
src/components/SelectIcon/style.module.css
src/pages/NewEvent/index.jsx
src/pages/NewEvent/style.module.css
src/test/Kobi.jsx

Validation for filling out the entire form, the save button is inactive until everything is entered correctlyValidation for filling out the entire form, the save button is inactive until everything is entered correctly

Validition-unable-button

---

src/pages/ViewEvent/index.jsx
src/pages/ViewEvent/style.module.css

added advertisers info to admin 3

added advertisers info to admin 3

---

src/components/SelectIcon/index.jsx
src/pages/NewEvent/index.jsx

fix selectIcon error

---

src/components/MultiSelect/index.jsx
src/pages/NewEvent/index.jsx

bugs fix in "place" and "summery"

Localstorge

---

public/index.html
src/components/EventCard/style.module.css
src/index.css

adding app.body to fix font family

adding app.body

---

src/pages/Registeretion/index.jsx
src/pages/Registeretion/style.module.css

fix logic in the Registration page and that fix the UI

validion of reg fix  logic and css

---

src/pages/NewEvent/index.jsx

Whatsapp or link

---

public/index.html
src/components/MultiSelect/index.jsx
src/pages/NewEvent/index.jsx

change the validion to th new description

nfinal validion
